DELETE http://localhost:3001/api/blogs/64a3be36faee7489fa5d1dd0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZyYW5raWUiLCJpZCI6IjY0YTNiNDkxZGU3NzQzNjg5NThmNjliZSIsImlhdCI6MTY4ODUxODY0MX0.mLbtn98ftu9OpUo4921Cu2Rvm7Vi1Z433ZY6c0eLmWI
